### ISSUE TITLE
[Refactor] Separate Production-Specific Secrets in `.env` Creation for Deployment

### ISSUE THREAD

**Issue by limJhyeok** [limJhyeok/Essay-Feedback-Writer#30]
**Description:**

Update the GitHub Actions workflow for production deployment to cleanly separate and explicitly define production-specific secrets when generating the `.env` file. This improves maintainability, clarity, and future scalability (e.g. for staging or dev environments).

**Current Behaviour:**

Currently, the `.env` file is generated using a mixture of general and production values without clear distinction. Several variables (e.g. `SECRET_KEY`, `FIRST_SUPERUSER`, `SMTP_*`, `POSTGRES_*`) are sourced from non-environment-specific secrets, making it harder to reason about or extend to other environments.

```yaml
# Example of current structure
env:
  ENVIRONMENT: production
  DOMAIN: ${{ secrets.DOMAIN_PRODUCTION }}
  ...
steps:
  - name: Create .env file
    run: |
      echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
      echo "FIRST_SUPERUSER=${{ secrets.FIRST_SUPERUSER }}" >> .env
      ...
```

**Proposed Change:**

Update the `.env` creation logic to clearly and exclusively use production-specific secrets. This isolates environment contexts, reduces the risk of misconfiguration, and aligns with best practices for secret management.

### Key Updates:

* Remove `env:` block entirely.
* Use `secrets.*_PRODUCTION` variants explicitly during `.env` creation.
* Use hardcoded `ENVIRONMENT=production` where applicable.

```yaml
# New structure
steps:
  - name: Create .env file
    run: |
      echo "ENVIRONMENT=production" >> .env
      echo "SECRET_KEY=${{ secrets.SECRET_KEY_PRODUCTION }}" >> .env
      echo "FIRST_SUPERUSER=${{ secrets.FIRST_SUPERUSER_PRODUCTION }}" >> .env
      ...
```

**Benefits:**

* ✅ Environment-specific secrets are clearly scoped.
* ✅ Safer deployment by reducing reliance on ambiguous shared secrets.
* ✅ Easier to extend for staging, dev, or testing workflows.
* ✅ Better separation of concerns and maintenance hygiene.

**Checklist:**

* [ ] Update `.env` generation in `deploy-production.yml`.
* [ ] Confirm all production secrets are defined in GitHub repo settings.
